/* eslint-disable @typescript-eslint/no-explicit-any */

import { z } from "zod";
import { PaymentMethod, OrderStatus } from "../common/constants";
import { AddressSchema } from "../zod/orderValidation";
import { IProductOrderItem } from "./Product";

// Infer the type from the addressSchema
type Address = z.infer<typeof AddressSchema>;

export interface IPreOrder {
  payment: boolean;
  userId: string;
  items: IProductOrderItem[];
  amount: number;
  address: Address;
  paymentMethod: PaymentMethod;
  date: number;
}

//Generated by Copilot lol
export interface IOrder extends IPreOrder {
  _id?: string;
  status: OrderStatus;
}

export interface OrderProductItem extends IProductOrderItem {
  status: string;
  payment: boolean;
  paymentMethod: string;
  date: number;
}
