/* eslint-disable @typescript-eslint/no-explicit-any */

import { ProductOrderItem } from "./Product";

export interface IPreOrder {
  payment: boolean;
  userId: string;
  items: IProductOrderItem[];
  amount: number;
  address: Object;
  paymentMethod: string;
  date: number;
}

//Generated by Copilot lol
export interface IOrder extends IPreOrder {
  _id?: string;
  status: string;
}

export interface OrderProductItem extends ProductOrderItem {
  status: string;
  payment: boolean;
  paymentMethod: string;
  date: number;
}
