import mongoose from "mongoose";

//Generated by Copilot lol
export interface IProduct {
  name: string;
  description: string;
  price: number;
  image: string[]; // Specify the exact type if known
  category: string;
  subCategory: string;
  sizes: string[]; // Specify the exact type if known
  bestseller?: boolean; // Optional field
  date: number;
}

const productSchema = new mongoose.Schema({
  name: { type: String, required: true },
  description: { type: String, required: true },
  price: { type: Number, required: true },
  image: { type: Array, required: true },
  category: { type: String, required: true },
  subCategory: { type: String, required: true },
  sizes: { type: Array, required: true },
  bestseller: { type: Boolean },
  date: { type: Number, required: true },
});

const ProductModel =
  mongoose.models.product || mongoose.model("product", productSchema);

export default ProductModel;
