/** This is generated by AI, given either a sample User response from Backend. Or Using the UserSchema */
export interface IUser {
  _id: string;
  name: string;
  email: string;
  password: string;
  city: string;
  state: string;
  country: string;
  occupation: string;
  phoneNumber: string;
  transactions: string[];
  role: string;
}
