export interface SetTokenProps {
  setToken: React.Dispatch<React.SetStateAction<string>>;
}

export interface TokenProps {
  token: string; //no token is equivalent to ""
}

//Generated by Copilot, copied from backend/models/productModel.ts
export interface IProduct {
  _id: string;
  name: string;
  description: string;
  price: number;
  image: string[]; // Specify the exact type if known
  category: string;
  subCategory: string;
  sizes: string[]; // Specify the exact type if known
  bestseller?: boolean; // Optional field
  date: number;
}
